[manager]
prepend_keymap= [
  { on = [ "O" ], run = "back" },
	{ on = [ "I" ], run = "forward" },
  { on = [ "Q"], run='shell "$SHELL" --block --confirm', desc='Drop to shell'},
  { on = [ "l"], run='plugin --sync smart-enter', desc='Enter the child directory, or open the file'},
  { on = [ "F"], run='plugin smart-fitler', desc='Smart filter'},
  { on = [ "R"], run='plugin --sync max-preview', desc='Maximize or restore preview'},
  { on = [ "f"], run='plugin jump-to-char', desc='Jump to char'},
  { on = [ "<C-d>"], run='plugin diff', desc='Diff the selected with the hover file'},
  { on = [ "c", 'm'], run='plugin chmod', desc='Chmod on selected files'}
]
